### ISSUE TITLE
No pass reports since June 2014

### ISSUE THREAD

**Issue by eserte** [sanko/www-thisismyjam#1]
A datetime-sorted overview of CPAN Testers reports: http://matrix.cpantesters.org/?dist=WWW-ThisIsMyJam;reports=1#sl=7,1
Currently the last pass report was on 2014-06-08.

**Comment by sanko** [comment]
Yeah, it doesn't matter seeing as TIMJ shut down a year or so ago.

I'll just let PAUSE delete the dists and mark this as resolved.

**Comment by eserte** [comment]
Good move!
